pub mod attachment;
pub mod automation;
pub mod config;
pub mod context;
pub mod diff;
pub mod file_tree;
pub mod git;
pub mod kanban;
pub mod mcp;
pub mod messages;
pub mod notify;
pub mod preset;
pub mod project;
pub mod pty;
pub mod skills;
pub mod workspace;

pub use attachment::attachment_create;
pub use automation::automation_run;
pub use config::config_load;
pub use context::context_usage;
pub use diff::{diff_get, diff_stage_hunk, diff_unstage_hunk};
pub use file_tree::file_tree;
pub use git::{git_branches, git_commit, git_diff_stat, git_log, git_stash_list};
pub use kanban::{kanban_list, kanban_upsert};
pub use mcp::{mcp_list, mcp_start, mcp_stop};
pub use messages::{message_append, messages_list};
pub use notify::notify_send;
pub use preset::{preset_launch, preset_list, preset_save_current};
pub use project::{project_add, project_list};
pub use pty::{pty_kill, pty_resize, pty_spawn, pty_write};
pub use skills::{skills_list, skills_run};
pub use workspace::{workspace_create, workspace_destroy, workspace_list};
