import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { SettingsGroup } from "../primitives/SettingsGroup";
import { SettingsRow } from "../primitives/SettingsRow";
import { SettingsToggle } from "../primitives/SettingsToggle";
import { SettingsSelect } from "../primitives/SettingsSelect";
import { useSettings } from "@/lib/stores/settings";
import { resetFirstRun } from "@/lib/tauri";

const BACKENDS = [
  { value: "claude", label: "Claude" },
  { value: "gemini", label: "Gemini" },
  { value: "codex", label: "Codex" },
  { value: "pi", label: "Pi" },
  { value: "other", label: "Other (custom binary)" },
];

export default function GeneralSettings() {
  const [defaultBackend, setDefaultBackend] = useSettings("general.defaultBackend", "claude");
  const [binPath, setBinPath] = useSettings("general.defaultBackendBinPath", "");
  const [defaultBranch, setDefaultBranch] = useSettings("general.defaultBranch", "origin/main");
  const [namingScheme, setNamingScheme] = useSettings("general.namingScheme", "maverick/{feature-name}");
  const [restore, setRestore] = useSettings("general.restoreSession", true);

  return (
    <div data-testid="general-settings" className="space-y-5">
      <SettingsGroup title="Defaults" description="Applied when a workspace is created without a preset.">
        <SettingsRow
          title="Default backend"
          description="The AI CLI used when no backend is specified in the preset."
          control={
            <SettingsSelect
              label="Default backend"
              value={defaultBackend}
              onValueChange={setDefaultBackend}
              options={BACKENDS}
              data-testid="general-default-backend"
            />
          }
        />
        {defaultBackend === "other" ? (
          <SettingsRow
            title="Custom binary path"
            description="Absolute path to the executable Maverick should launch for this backend."
            control={
              <Input
                data-testid="general-default-backend-binpath"
                value={binPath}
                onChange={(e) => setBinPath(e.target.value)}
                placeholder="/usr/local/bin/my-agent"
                className="w-72 font-mono"
              />
            }
          />
        ) : null}
        <SettingsRow
          title="Default base branch"
          description="New worktrees are forked from this branch."
          control={
            <Input
              data-testid="general-default-branch"
              value={defaultBranch}
              onChange={(e) => setDefaultBranch(e.target.value)}
              className="w-72"
            />
          }
        />
        <SettingsRow
          title="Workspace naming scheme"
          description="{feature-name} is generated by the AI from your prompt. Other tokens: {branch}, {backend}, {date}."
          control={
            <Input
              data-testid="general-naming"
              value={namingScheme}
              onChange={(e) => setNamingScheme(e.target.value)}
              placeholder="maverick/{feature-name}"
              className="w-72 font-mono"
            />
          }
        />
      </SettingsGroup>

      <SettingsGroup title="Startup">
        <SettingsRow
          title="Restore last session on startup"
          description="Re-open the workspaces that were active when you last closed Maverick."
          control={
            <SettingsToggle
              label="Restore last session"
              checked={restore}
              onCheckedChange={setRestore}
              data-testid="general-restore"
            />
          }
        />
      </SettingsGroup>

      <SettingsGroup title="First-run" description="Re-trigger the welcome wizard.">
        <SettingsRow
          title="Run setup wizard"
          description="Walks you through directory creation, permissions, theme, and default backend."
          control={
            <Button
              variant="outline"
              size="sm"
              data-testid="general-run-setup-wizard"
              onClick={() => void resetFirstRun()}
            >
              Run setup wizard
            </Button>
          }
        />
      </SettingsGroup>
    </div>
  );
}
